
// @ts-nocheck
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { corsHeaders, sendEmail } from "./email-service.ts";

// Helper function to extract files from FormData
async function getFilesFromFormData(formData: FormData) {
  const files = [];
  
  // Extract all files from the FormData
  for (const [key, value] of formData.entries()) {
    if (key.startsWith('file') && value instanceof File) {
      // Convert File to Base64 for email attachment
      const arrayBuffer = await value.arrayBuffer();
      const base64 = btoa(
        new Uint8Array(arrayBuffer)
          .reduce((data, byte) => data + String.fromCharCode(byte), '')
      );
      
      files.push({
        name: value.name,
        type: value.type,
        size: value.size,
        content: base64
      });
    }
  }
  
  return files;
}

const handler = async (req: Request): Promise<Response> => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }
  
  try {
    // Extract FormData from request
    const formData = await req.formData();
    
    // Get data from FormData
    const name = formData.get("name") as string;
    const email = formData.get("email") as string;
    const phone = formData.get("phone") as string;
    const company = formData.get("company") as string;
    const address = formData.get("address") as string;
    const planName = formData.get("planName") as string;
    const to = formData.get("to") as string || "truckmatecmms@gmail.com";
    
    // Extract files from FormData
    const files = await getFilesFromFormData(formData);
    
    console.log(`Processing payment proof from ${name}, ${email} for plan: ${planName}`);
    console.log(`Number of files: ${files.length}`);
    
    // Prepare email
    const emailData = {
      to: to,
      subject: `Payment proof from ${name} for ${planName} Plan`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 5px;">
          <h2 style="color: #1a73e8; margin-bottom: 20px;">New Payment Proof</h2>
          
          <p>A customer has sent a payment proof for TruckMate CMMS.</p>
          
          <div style="background-color: #f9f9f9; padding: 15px; border-radius: 4px; margin: 15px 0;">
            <p><strong>Name:</strong> ${name}</p>
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Phone:</strong> ${phone}</p>
            <p><strong>Company:</strong> ${company}</p>
            <p><strong>Address:</strong> ${address}</p>
            <p><strong>Selected Plan:</strong> ${planName}</p>
            <p><strong>Number of attachments:</strong> ${files.length}</p>
          </div>
          
          <p style="color: #666; font-size: 14px;">This notification was automatically generated by the TruckMate CMMS system.</p>
        </div>
      `
    };
    
    // If we have files, add them as attachments
    if (files.length > 0) {
      emailData.attachments = files.map(file => ({
        filename: file.name,
        content: file.content,
        encoding: 'base64',
        type: file.type
      }));
    }
    
    // Send email using the sendEmail function
    const result = await sendEmail(emailData);
    console.log("Email sending result:", result);
    
    if (!result.success) {
      throw new Error(result.message || "Failed to send email");
    }
    
    return new Response(JSON.stringify({
      success: true,
      message: "Payment proof sent successfully"
    }), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        ...corsHeaders,
      },
    });
    
  } catch (error: any) {
    console.error("Error processing payment proof:", error);
    return new Response(
      JSON.stringify({ 
        success: false,
        error: error.message 
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

serve(handler);
