// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnigsoflxmqoitfwwkrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uaWdzb2ZseG1xb2l0Znd3a3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjMxMzQsImV4cCI6MjA2MDczOTEzNH0.060WTA-9P7qt1L_9Y45KclqifQGkCnK0nKYcf6g8Svg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);